### ISSUE TITLE
这是一款通过算法来提速的高速下载器, 请问是挖矿算法吗, 23333

### ISSUE THREAD

**Issue by WangYihang** [high-speed-downloader/high-speed-downloader#5]
![image](https://user-images.githubusercontent.com/16917636/34336022-9d2a0d60-e98e-11e7-976d-cfeef4c26a8b.png)

> 希望公开道歉, 已举报

**Comment by dirklu** [comment]
已经卸载，行为有点无耻

**Comment by WangYihang** [comment]
噗...还有删除评论这种操作...吃相别太难看啊老铁
