### ISSUE TITLE
速度很快！！下载过程中强制关闭后，再次启动就会报错，无法添加任务下载了！

### ISSUE THREAD

**Issue by qiushicai** [high-speed-downloader/high-speed-downloader#8]
卸载重新安装也不行！一启动就报错。

**Comment by qiushicai** [comment]
![snipaste_2018-01-07_12-20-22](https://user-images.githubusercontent.com/20509980/34646520-3e63b238-f3a5-11e7-8713-9a7d6a7b1d86.jpg)

**Comment by high-speed-downloader** [comment]
打开 C:\Users\你的用户名\.downloader 文件夹
把 tasks5 文件删除了,该BUG会在下个版本彻底修复
