### ISSUE TITLE
发现一个错误（下载过程中改变百度云中文件夹位置后，下载无法启动），麻烦请协助

### ISSUE THREAD

**Issue by shadowurus** [high-speed-downloader/high-speed-downloader#9]
这是一个非常好用的软件，对于开发者致以崇高敬意
但是在使用过程中发现了一个bug，麻烦需要解决一下
情形是这样的，我用的是macOS，下载了一个文件夹，里面有几十个文件，在下载过程中，我把百度云中的文件夹移动了一个位置，同时改了一下文件夹的名称，结果下载完正在下载的文件后，之后的文件不再下载，显示速度为0，且部分任务无法停止，无法删除，一点暂停按钮软件就死了
以上BUG，不知道是偶然还是必然，烦请进行修正
另外，我用cleanmymac卸载该软件，但是重新安装后却出现了之前的下载列表（依然是无法下载无法删除状态），由于无法知道下载列表放于何处，我无法重置该软件，因此无法再使用，如果可以的话，能否告诉我如何重置下载列表或删除列表文件吗，不甚感激

**Comment by dxcweb** [comment]
抱歉给您带来不便下一版本将修复该问题。下载列表存放在~/.downloader/tasks5 文件里。你可以rm ~/.downloader/tasks5 使其恢复正常

**Comment by high-speed-downloader** [comment]
抱歉给您带来不便下一版本将修复该问题。下载列表存放在~/.downloader/tasks5 文件里。你可以rm ~/.downloader/tasks5 使其恢复正常

**Comment by shadowurus** [comment]
非常感谢～
